name: berlin
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.78
  - git=2.40.1
  - graphviz=8.0.5
  - jupyter=1.0.0
  - nextalign=2.14.0
  - nextclade=2.14.0
  - openpyxl=3.0.9
  - pandas=2.0.1
  - python=3.10.11
  - snakemake=7.25.4
